name: Docc

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Docc for GitHub Pages
    runs-on: macos-latest
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: 5.6
      - uses: actions/checkout@v3
      - name: Get package name ## This assumes 1 package in this library
        id: get_package
        run: |
          LIBRARY_NAME=$(swift package describe | grep 'Name: ' | grep -v 'Tests' | awk '{print $2}' | head -n 1)
          echo "::set-output name=name::$(echo $LIBRARY_NAME)"
      - name: Create Docc
        run: |
          swift package --allow-writing-to-directory ./docs/docc generate-documentation --target $LIBRARY_NAME --output-path ./docs/docc --transform-for-static-hosting --hosting-base-path "$REPO_NAME/docc"
        env:
          LIBRARY_NAME: ${{ steps.get_package.outputs.name  }}
          REPO_NAME: ${{ github.event.repository.name }}
      - name: Publish generated doc
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated source code documentation generated with Docc
